[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.44.0"
hooks = [
  { id = "typos" },
]


[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.7"

[[repos.hooks]]
id = "ruff-check"
args = [
  # "--fix", "--show-fixes",
  "--config", "backend/pyproject.toml"
]
files = '^backend'

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.12"

[[repos.hooks]]
id = "uv-lock"
args = ["--directory", "backend"]
files = '^backend/(uv\.lock|pyproject\.toml|uv\.toml)$'


[[repos]]
repo = "local"

[[repos.hooks]]
id = "local-ty"
name = "ty check"
language = "system"
entry = "uv --directory backend run ty check"
files = '^backend' # maybe increase specificity
pass_filenames = false

[[repos.hooks]]
id = "local-pytest" # remove if run time ever gets annoying
name = "pytest"
language = "system"
entry = "uv --directory backend run pytest -q --tb=short --inline-snapshot=disable" # maybe change arguments
pass_filenames = false
files = '^backend'

[[repos.hooks]]
id = "local-eslint"
name = "ESLint"
language = "system"
entry = "pnpm --dir frontend run lint"
pass_filenames = false
files = '^frontend/src/'

[[repos.hooks]]
id = "generate-api-client" # maybe migrate to toml 1.1 in the future
name = "Generate API client"
language = "system"
entry = "just generate" # maybe improve so doesnt fail if pnpm isnt installed (either switch approach entirely or backup to npm)
pass_filenames = false
files = '^backend/app/'
