// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteNotesData, DeleteNotesErrors, DeleteNotesResponses, GetCoursesData, GetCoursesErrors, GetCoursesResponses, GetPdfContentData, GetPdfContentErrors, GetPdfContentResponses, GetPdfsData, GetPdfsErrors, GetPdfsResponses, ParsePdfToPlannerData, ParsePdfToPlannerErrors, ParsePdfToPlannerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get PDF content
 */
export const getPdfContent = <ThrowOnError extends boolean = false>(options: Options<GetPdfContentData, ThrowOnError>) => (options.client ?? client).get<GetPdfContentResponses, GetPdfContentErrors, ThrowOnError>({ url: '/pdfs/{file_id}', ...options });

/**
 * Parse PDF and add to planner
 */
export const parsePdfToPlanner = <ThrowOnError extends boolean = false>(options: Options<ParsePdfToPlannerData, ThrowOnError>) => (options.client ?? client).post<ParsePdfToPlannerResponses, ParsePdfToPlannerErrors, ThrowOnError>({ url: '/pdfs/{file_id}', ...options });

/**
 * Get Courses
 */
export const getCourses = <ThrowOnError extends boolean = false>(options?: Options<GetCoursesData, ThrowOnError>) => (options?.client ?? client).get<GetCoursesResponses, GetCoursesErrors, ThrowOnError>({ url: '/courses', ...options });

/**
 * List course PDFs
 */
export const getPdfs = <ThrowOnError extends boolean = false>(options: Options<GetPdfsData, ThrowOnError>) => (options.client ?? client).get<GetPdfsResponses, GetPdfsErrors, ThrowOnError>({ url: '/courses/{course_id}/pdfs', ...options });

/**
 * Delete all planner notes for a course
 */
export const deleteNotes = <ThrowOnError extends boolean = false>(options: Options<DeleteNotesData, ThrowOnError>) => (options.client ?? client).delete<DeleteNotesResponses, DeleteNotesErrors, ThrowOnError>({ url: '/courses/{course_id}/notes', ...options });
