// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteNotesCoursesCourseIdNotesDeleteData, DeleteNotesCoursesCourseIdNotesDeleteErrors, DeleteNotesCoursesCourseIdNotesDeleteResponses, GetCoursesCoursesGetData, GetCoursesCoursesGetErrors, GetCoursesCoursesGetResponses, GetPdfContentPdfsFileIdGetData, GetPdfContentPdfsFileIdGetErrors, GetPdfContentPdfsFileIdGetResponses, GetPdfsCoursesCourseIdPdfsGetData, GetPdfsCoursesCourseIdPdfsGetErrors, GetPdfsCoursesCourseIdPdfsGetResponses, ParsePdfToPlannerPdfsFileIdPostData, ParsePdfToPlannerPdfsFileIdPostErrors, ParsePdfToPlannerPdfsFileIdPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get PDF content
 */
export const getPdfContentPdfsFileIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPdfContentPdfsFileIdGetData, ThrowOnError>) => (options.client ?? client).get<GetPdfContentPdfsFileIdGetResponses, GetPdfContentPdfsFileIdGetErrors, ThrowOnError>({ url: '/pdfs/{file_id}', ...options });

/**
 * Parse PDF and add to planner
 */
export const parsePdfToPlannerPdfsFileIdPost = <ThrowOnError extends boolean = false>(options: Options<ParsePdfToPlannerPdfsFileIdPostData, ThrowOnError>) => (options.client ?? client).post<ParsePdfToPlannerPdfsFileIdPostResponses, ParsePdfToPlannerPdfsFileIdPostErrors, ThrowOnError>({ url: '/pdfs/{file_id}', ...options });

/**
 * Get Courses
 */
export const getCoursesCoursesGet = <ThrowOnError extends boolean = false>(options?: Options<GetCoursesCoursesGetData, ThrowOnError>) => (options?.client ?? client).get<GetCoursesCoursesGetResponses, GetCoursesCoursesGetErrors, ThrowOnError>({ url: '/courses', ...options });

/**
 * List course PDFs
 */
export const getPdfsCoursesCourseIdPdfsGet = <ThrowOnError extends boolean = false>(options: Options<GetPdfsCoursesCourseIdPdfsGetData, ThrowOnError>) => (options.client ?? client).get<GetPdfsCoursesCourseIdPdfsGetResponses, GetPdfsCoursesCourseIdPdfsGetErrors, ThrowOnError>({ url: '/courses/{course_id}/pdfs', ...options });

/**
 * Delete all planner notes for a course
 */
export const deleteNotesCoursesCourseIdNotesDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteNotesCoursesCourseIdNotesDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteNotesCoursesCourseIdNotesDeleteResponses, DeleteNotesCoursesCourseIdNotesDeleteErrors, ThrowOnError>({ url: '/courses/{course_id}/notes', ...options });
