// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BulkDeleteResult
 */
export type BulkDeleteResult = {
    /**
     * Total
     */
    total: number;
    /**
     * Deleted
     */
    deleted: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * Course
 */
export type Course = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Course Code
     */
    course_code: string;
    [key: string]: unknown;
};

/**
 * CourseFile
 */
export type CourseFile = {
    /**
     * File Id
     */
    file_id: number;
    /**
     * Item Id
     */
    item_id: number;
    /**
     * Title
     */
    title: string;
    [key: string]: unknown;
};

/**
 * Eng10Schedule
 */
export type Eng10Schedule = {
    /**
     * Odd
     */
    odd: Array<PlannerNote>;
    /**
     * Even
     */
    even: Array<PlannerNote>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

export type ParsedDate = string;

/**
 * PlannerNote
 */
export type PlannerNote = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    todo_date: ParsedDate | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetPdfContentPdfsFileIdGetData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/pdfs/{file_id}';
};

export type GetPdfContentPdfsFileIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPdfContentPdfsFileIdGetError = GetPdfContentPdfsFileIdGetErrors[keyof GetPdfContentPdfsFileIdGetErrors];

export type GetPdfContentPdfsFileIdGetResponses = {
    /**
     * Successful Response
     */
    200: Eng10Schedule;
};

export type GetPdfContentPdfsFileIdGetResponse = GetPdfContentPdfsFileIdGetResponses[keyof GetPdfContentPdfsFileIdGetResponses];

export type ParsePdfToPlannerPdfsFileIdPostData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query: {
        /**
         * Day
         */
        day: 'odd' | 'even';
        /**
         * Course Id
         */
        course_id?: number | null;
    };
    url: '/pdfs/{file_id}';
};

export type ParsePdfToPlannerPdfsFileIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParsePdfToPlannerPdfsFileIdPostError = ParsePdfToPlannerPdfsFileIdPostErrors[keyof ParsePdfToPlannerPdfsFileIdPostErrors];

export type ParsePdfToPlannerPdfsFileIdPostResponses = {
    /**
     * Response Parse Pdf To Planner Pdfs  File Id  Post
     *
     * Successful Response
     */
    200: Array<PlannerNote>;
};

export type ParsePdfToPlannerPdfsFileIdPostResponse = ParsePdfToPlannerPdfsFileIdPostResponses[keyof ParsePdfToPlannerPdfsFileIdPostResponses];

export type GetCoursesCoursesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Inactive
         */
        inactive?: boolean;
    };
    url: '/courses';
};

export type GetCoursesCoursesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCoursesCoursesGetError = GetCoursesCoursesGetErrors[keyof GetCoursesCoursesGetErrors];

export type GetCoursesCoursesGetResponses = {
    /**
     * Response Get Courses Courses Get
     *
     * Successful Response
     */
    200: Array<Course>;
};

export type GetCoursesCoursesGetResponse = GetCoursesCoursesGetResponses[keyof GetCoursesCoursesGetResponses];

export type GetPdfsCoursesCourseIdPdfsGetData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: number;
    };
    query?: never;
    url: '/courses/{course_id}/pdfs';
};

export type GetPdfsCoursesCourseIdPdfsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPdfsCoursesCourseIdPdfsGetError = GetPdfsCoursesCourseIdPdfsGetErrors[keyof GetPdfsCoursesCourseIdPdfsGetErrors];

export type GetPdfsCoursesCourseIdPdfsGetResponses = {
    /**
     * Response Get Pdfs Courses  Course Id  Pdfs Get
     *
     * Successful Response
     */
    200: Array<CourseFile>;
};

export type GetPdfsCoursesCourseIdPdfsGetResponse = GetPdfsCoursesCourseIdPdfsGetResponses[keyof GetPdfsCoursesCourseIdPdfsGetResponses];

export type DeleteNotesCoursesCourseIdNotesDeleteData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: number;
    };
    query?: never;
    url: '/courses/{course_id}/notes';
};

export type DeleteNotesCoursesCourseIdNotesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNotesCoursesCourseIdNotesDeleteError = DeleteNotesCoursesCourseIdNotesDeleteErrors[keyof DeleteNotesCoursesCourseIdNotesDeleteErrors];

export type DeleteNotesCoursesCourseIdNotesDeleteResponses = {
    /**
     * Successful Response
     */
    200: BulkDeleteResult;
};

export type DeleteNotesCoursesCourseIdNotesDeleteResponse = DeleteNotesCoursesCourseIdNotesDeleteResponses[keyof DeleteNotesCoursesCourseIdNotesDeleteResponses];
