// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_preview_uploaded_schedule
 */
export type BodyPreviewUploadedSchedule = {
    /**
     * Pdf
     */
    pdf: Blob | File;
};

/**
 * BulkDeleteResult
 */
export type BulkDeleteResult = {
    /**
     * Total
     */
    total: number;
    /**
     * Deleted
     */
    deleted: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * Course
 */
export type Course = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Course Code
     */
    course_code: string;
    [key: string]: unknown;
};

/**
 * CourseFile
 */
export type CourseFile = {
    /**
     * File Id
     */
    file_id: number;
    /**
     * Item Id
     */
    item_id: number;
    /**
     * Title
     */
    title: string;
    [key: string]: unknown;
};

/**
 * Eng10Schedule
 */
export type Eng10Schedule = {
    /**
     * Odd
     */
    odd: Array<PlannerNote>;
    /**
     * Even
     */
    even: Array<PlannerNote>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

export type ParsedDate = string;

/**
 * PlannerNote
 */
export type PlannerNote = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Course Id
     */
    course_id?: number | null;
    todo_date: ParsedDate | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type PreviewScheduleData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/pdfs/{file_id}';
};

export type PreviewScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewScheduleError = PreviewScheduleErrors[keyof PreviewScheduleErrors];

export type PreviewScheduleResponses = {
    /**
     * Successful Response
     */
    200: Eng10Schedule;
};

export type PreviewScheduleResponse = PreviewScheduleResponses[keyof PreviewScheduleResponses];

export type PreviewUploadedScheduleData = {
    body: BodyPreviewUploadedSchedule;
    path?: never;
    query?: never;
    url: '/pdfs/upload';
};

export type PreviewUploadedScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewUploadedScheduleError = PreviewUploadedScheduleErrors[keyof PreviewUploadedScheduleErrors];

export type PreviewUploadedScheduleResponses = {
    /**
     * Successful Response
     */
    200: Eng10Schedule;
};

export type PreviewUploadedScheduleResponse = PreviewUploadedScheduleResponses[keyof PreviewUploadedScheduleResponses];

export type AddScheduleToPlannerData = {
    body: Eng10Schedule;
    path?: never;
    query: {
        /**
         * Day
         */
        day: 'odd' | 'even';
        /**
         * Course Id
         */
        course_id?: number | null | null;
    };
    url: '/pdfs/add';
};

export type AddScheduleToPlannerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddScheduleToPlannerError = AddScheduleToPlannerErrors[keyof AddScheduleToPlannerErrors];

export type AddScheduleToPlannerResponses = {
    /**
     * Response Add Schedule To Planner
     *
     * Successful Response
     */
    200: Array<PlannerNote>;
};

export type AddScheduleToPlannerResponse = AddScheduleToPlannerResponses[keyof AddScheduleToPlannerResponses];

export type GetCoursesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Inactive
         */
        inactive?: boolean;
    };
    url: '/courses';
};

export type GetCoursesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCoursesError = GetCoursesErrors[keyof GetCoursesErrors];

export type GetCoursesResponses = {
    /**
     * Response Get Courses
     *
     * Successful Response
     */
    200: Array<Course>;
};

export type GetCoursesResponse = GetCoursesResponses[keyof GetCoursesResponses];

export type GetPdfsData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: number;
    };
    query?: never;
    url: '/courses/{course_id}/pdfs';
};

export type GetPdfsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPdfsError = GetPdfsErrors[keyof GetPdfsErrors];

export type GetPdfsResponses = {
    /**
     * Response Get Pdfs
     *
     * Successful Response
     */
    200: Array<CourseFile>;
};

export type GetPdfsResponse = GetPdfsResponses[keyof GetPdfsResponses];

export type DeleteNotesData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: number;
    };
    query?: never;
    url: '/courses/{course_id}/notes';
};

export type DeleteNotesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNotesError = DeleteNotesErrors[keyof DeleteNotesErrors];

export type DeleteNotesResponses = {
    /**
     * Successful Response
     */
    200: BulkDeleteResult;
};

export type DeleteNotesResponse = DeleteNotesResponses[keyof DeleteNotesResponses];
